### ISSUE TITLE
OPDS Catalog breaks in Owncloud 8

### ISSUE THREAD

**Issue by clarjon1** [Yetangitu/owncloud-apps#5] opened 2015-02-10 14:24 UTC
Hello,

As of the upgrade to Owncloud 8, the OPDS app has stopped working.  There are a couple of bugs which I shall go over.

Firstly, when I try to access the OPDS url, either through a browser or through my reader of choice, I am redirected to a files list. This is quite a large bug, as it means I cannot use the library system anymore.

The second bug is a lot more minor: http://i.imgur.com/rAkGmUK.png  the sidebar is a bit wonky here.

Please let me know if you need more info.

**Comment by Yetangitu** [comment] 2015-02-10 21:15
I'll address this once I have OC8 on my system. The 'redirect to files list' seems to affect more apps, this might be an OC bug.

**Comment by Yetangitu** [comment] 2015-02-11 01:02
I committed an initial port to OC8 a few moments ago. While OPDS catalog seems to work OK ('works for me ™'), Reader does not yet do what it should. Now it is getting late, and tomorrow - or I should say today - is another day...

**Comment by buzzra** [comment] 2015-02-12 14:52
I am having problems also after upgrade to OC8. FBReader just shows "catalogis empty, sorry" when I try to connect. How do I update to the new port, if there is no version number change and thus no update button in the interface?

Thanks,
buzz

**Comment by Yetangitu** [comment] 2015-02-12 19:45
Try the new version I just committed (v0.6.2), also in the apps repository. It 'works for me ™'...

**Comment by clarjon1** [comment] 2015-02-12 19:59
The file isn't showing up in the dist directory, and the apps repository 404's, trying to get to the non-existant file in the dist directory.

**Comment by Yetangitu** [comment] 2015-02-12 23:47
Try again, yet another new version (0.6.4), now includes option to add Google Books API key and even less log spam...

**Comment by buzzra** [comment] 2015-02-13 14:53
@Yetangitu , Thanks for the support. Sorry It took so long for me to try and get back to you.

I tried the 0.6.2 version, and then the 0.6.4 version. When I click the update button on the OC8 Apps page, I get "error while updating app". I did not see anything in the log, but I will investigate further.

buzz

**Comment by Yetangitu** [comment] 2015-02-13 15:57
These problems might be caused by the following:

https://www.ssllabs.com/ssltest/analyze.html?d=www.owncloud.org&s=50.30.33.236

The certificate for *.owncloud.org seems to be revoked, and no new certificate is in place yet.

Try a manual update: download the tarball, move the old version out of the way and unpack it in the apps directory. Change ownership to that of your web server (if you care about future 'automatic' updates, that is... personally I keep the apps directory read-only for the server (I do manual updates)). Run an update (./occ upgrade --skip-migration-test in the owncloud directory, make sure you have a backup of anything important,especially if you use '--skip-migration-test') and bask in the glory of a resurrected OPDS catalog.

**Comment by Yetangitu** [comment] 2015-02-13 20:51
The certificate is back, maybe it works now?

**Comment by buzzra** [comment] 2015-02-13 22:52
I still get error. I will do manual update as you suggested, but it will be later tonight. Sorry I can't help and test quicker. Stupid work.... ;-)

**Comment by Yetangitu** [comment] 2015-02-18 00:54
Any progress?

**Comment by clarjon1** [comment] 2015-02-18 12:13
Catalog is working (except for thumbnail/cover art retrieval)

**Comment by Yetangitu** [comment] 2015-02-18 13:24
Which client do you use? To really test cover art, open the feed in a Gecko-based browser (Firefox et al) and try one of the 'pid' (cover) or 'tid' (thumbnail) links. Many clients have problems with covert art over authenticated and/or encrypted connections. This, unfortunately, is not something I can do anything about - the client needs to be fixed. Known working clients are eg. FBreader and Moon+ Reader on Android and KyBook and Marvin on iOS.

**Closed by Yetangitu** 2015-02-18 13:24 UTC
