### ISSUE TITLE
OC9.0.x/OPDS 0.6.15: File with id "<ID>" has not been found.

### ISSUE THREAD

**Issue by nRaecheR** [Yetangitu/owncloud-apps#18] opened 2016-06-06 07:31 UTC
I'm at 0.6.15 and I since my update to OC 9.0.x the app won't work anymore. It used to work for some versions without a problem but now I only get an error like 

```
File with id "<ID>" has not been found.
```
Here's the full error message from Moon+, same goes for access from a browser: 
```
No validated OPDS content, click here to see what's OPDS Catalog.

This application requires JavaScript for correct operation. Please enable JavaScript and reload the page.

ownCloud

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.


Technical details

Remote Address: 192.168.200.100Request ID: MXu6dTXr92+VpcARHnDcType: OCP\Files\NotFoundExceptionCode: 0Message: File with id "373959" has not been found.File: /var/www/owncloud/lib/private/files/view.phpLine: 1643

Trace

#0 /var/www/owncloud/lib/private/files/filesystem.php(906): OC\Files\View->getPath(373959) 
#1 /var/www/owncloud/apps/files_opds/lib/bookshelf.php(61): OC\Files\Filesystem::getPath(373959)
#2 /var/www/owncloud/apps/files_opds/lib/feed.php(63): OCA\Files_Opds\Bookshelf::get() 
#3 /var/www/owncloud/apps/files_opds/index.php(77): OCA\Files_Opds\Feed::serveFeed('E-Books', 4, 'root') 
#4 /var/www/owncloud/lib/private/route/route.php(154) : runtime-created function(1): require_once('/var/www/ownclo...') 
#5 [internal function]: __lambda_func() 
#6 /var/www/owncloud/lib/private/route/router.php(276): call_user_func('\x00lambda_463', Array) 
#7 /var/www/owncloud/lib/base.php(882): OC\Route\Router->match('/apps/files_opd...') 
#8 /var/www/owncloud/index.php(39): OC::handleRequest() 
#9 {main}

ownCloud – web services under your control

```

The given path "E-Books" is available and browsable in the files app as normal so it should be a genuine problem of the 'files_opds' app

**Comment by Yetangitu** [comment] 2016-06-06 08:10
Looks like you're not getting an OPDS feed but a web page - the javascript bit is a tell-talle sign. Which version (the .x) of OC are you using?

I'm a bit short in time right now but I'll look into this ASAP as there are by now several reports on this and related problems.

**Comment by nRaecheR** [comment] 2016-06-06 08:12
Thanks for your answer. OC is at 9.0.2 which is the latest to date.

**Comment by Yetangitu** [comment] 2016-06-06 08:38
OK, I'll try to find some time of of these nights to solve this.

**Comment by Yetangitu** [comment] 2016-06-14 10:49
Try to clear your personal bookshelf:

 - go to the personal settings page, OPDS section
 - select 'Clear Bookshelf' -> 'Yes, I really want to clear my personal bookshelf'

This will probably solve your problem in that OPDS Catalog will work again. You may also want to schedule a rescan as OC seems to have messed up fileid's.

**Comment by nRaecheR** [comment] 2016-06-14 11:43
Okay, i did that, now it's partly working. Moon+ and the browser interface are showing the top level directory structure of the library folder but when I try to descent into any of the subdirs the content of the top directory will be shown instead. 
Doing the same in the files app works as expected. The IDs in the URL for files_opds seem to be valid and unique.

**Comment by Yetangitu** [comment] 2016-06-14 12:20
Did you also schedule a rescan as I suggested?

What happens when you  - after scheduling a rescan - descend into a subtree using a browser? For this purpose a gecko-based browser (Firefox, Seamonkey, etc) works best as it allows full navigation.

**Comment by nRaecheR** [comment] 2016-06-14 12:40
I did perform a rescan from the personal settings page. When I descend into the Library the top level directory will be show again and again.

**Comment by Yetangitu** [comment] 2016-06-14 13:53
Does the log (both OC, container (fpm, etc) and webserver (errorlog)) show anything interesting when you try to navigate the tree?

**Comment by nRaecheR** [comment] 2016-06-15 04:48
These are the entries in the Apache2 log when trying to access the library from Firefox:

```
<ip-address> - <username> [15/Jun/2016:06:44:25 +0200] "GET /index.php/apps/files_opds/ HTTP/1.1" 200 1651 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
<ip-address> - <username> [15/Jun/2016:06:44:27 +0200] "GET /index.php/apps/files_opds/?id=directory HTTP/1.1" 200 1951 "https://domain.tld/index.php/apps/files_opds/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
<ip-address> - <username> [15/Jun/2016:06:44:29 +0200] "GET /index.php/apps/files_opds/?id=383245 HTTP/1.1" 200 1951 "https://domain.tld/index.php/apps/files_opds/?id=directory" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
<ip-address> - <username> [15/Jun/2016:06:44:34 +0200] "GET /index.php/apps/files_opds/?id=383301 HTTP/1.1" 200 1967 "https://domain.tld/index.php/apps/files_opds/?id=383245" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"

```
(Replaced some personal data with dummy data.


All other logs stay empty

**Comment by nRaecheR** [comment] 2016-06-22 05:28
Is there anything I could do to help you track down the problem like enabling additional debug options etc. Please let me know.

**Comment by nRaecheR** [comment] 2016-06-23 13:11
Ah, there is indeed an entry in the ownCloud log, I had misse it because I moved it to syslog logging. Here it is :

```
Jun 23 15:09:07 <servername> ownCloud[27647]: {PHP} Undefined variable: type at /var/www/owncloud/apps/files_opds/index.php#77

```

It repeats each time I try to access the subdir in the catalog.

**Comment by Yetangitu** [comment] 2016-06-23 14:37
That is just a notice the cause of which should have no negative effect on the functioning of OPDS Catalog. The warning is generated when, in the course of deciding which code path to take, neither a command word (like 'root' or 'bookshelf') nor a specific request type (like 'thumbnail' or 'cover') is found. The request is sent on without any defined type, the file node is checked and found to be a directory and the serveFeed function is called. This in turn uses a template which contains a default case for when $type is undefined. I should get rid of this warning by assigning a default value to $type (the whole $type mangling code is a bit haphazard and could do with some cleaning-up).

Do you have any other users on that OC instance? If so, does OPDS Catalog work for them? If not, try to create a test-user, enable OPDS Catalog for that user and configure it to point at some directory which contains some publications spread around several directories. Now try to navigate that catalog. If it works for that user it is clear that your problem stems from a corrupted database. If it does not, it could still be caused by a corrupted database but there might be other factors in play.

**Comment by nRaecheR** [comment] 2016-06-24 04:56
Okay, I've tested with another user on the same files shared to the user and it works normally. So it seems that the database for the first user is corrupted. My database is MariaDB. Could you please tell me which tables I need to drop to reset the app or user to defaults?

**Comment by Yetangitu** [comment] 2016-06-24 10:31
Good, now we're getting somewhere at least...

Before dropping any tables - which is the 'Windows-world' solution to any problems, just reinstall... - you could take a look at the preferences for your user (the one which doesn't work).

The following query examples assume that the prefix is set to 'oc_' (the default), if you use a different prefix you need to edit the examples before using them.

```
select * from oc_preferences where appid='files_opds' and userid='<YOUR_USERID>';
```

Don't forget to re-enable OPDS Catalog for your user and to set the library root directory to something sensible after issuing this command.
To reset only that user for OPDS Catalog you can use the following:

```
delete from oc_preferences where appid='files_opds' and userid='<YOUR_USERID>';
```

**Comment by Yetangitu** [comment] 2016-08-17 12:56
I assume this issue has been fixed so I'll close it...

**Closed by Yetangitu** 2016-08-17 12:56 UTC
