### ISSUE TITLE
CBZ/CBR viewer does not work on Nextcloud 13

### ISSUE THREAD

**Issue by psy-q** [Yetangitu/owncloud-apps#79] opened 2018-02-09 12:52 UTC
I just set up a fresh instance and Reader is set as default viewer for CBZ/CBR, but instead of opening the files in the browser, it still prompts to download them.

Is there an additional setting that's required?

**Comment by Yetangitu** [comment] 2018-02-11 12:54
No, it shoud 'just work'. Do the other renderers (EPUB and PDF) work as intended?

**Comment by seiichiro0185** [comment] 2018-02-15 12:54
I have the same Problem. PDF / EPUB work as intended, CBR/CBZ gets me a download Prompt instead. Settings in Nextcloud are active:

![grafik](https://user-images.githubusercontent.com/226729/36257557-b7590686-1257-11e8-94b7-8daaccbf7b55.png)

**Comment by returntrip** [comment] 2018-02-15 20:01
Same issue here. EPUB works fine but CBZ does not work (downloads pops up.

However, I tried to open a CBZ file from the "..." menu then pressing "View" and I get a strange window. See screenshots:

![selection_001](https://user-images.githubusercontent.com/14056122/36278153-346bbb9c-1293-11e8-8f40-c6fcde4de092.png)
![selection_002](https://user-images.githubusercontent.com/14056122/36278154-348ba344-1293-11e8-94f9-ddbf505f0561.png)

**Comment by Yetangitu** [comment] 2018-02-15 22:02
That strange window looks like the result of missing resources - scripts and CSS. I'll look into this when I find some time.

**Comment by seiichiro0185** [comment] 2018-02-16 14:16
I just tried the "View"-entry in the menu just now (somehow missed this way to manually invoke the Reader until now), and it works fine, so only changing the default action to viewing in the Reader seems not to work for me.

The broken output from @returntrip looks like the problem from Issue #58 , at least the screenshot looks exactly like what I got before changing my webserver config to the one from the Nextcloud Administration Manual.

**Comment by Yetangitu** [comment] 2018-02-16 20:36
Reader not wanting to become default is caused by a simple typo in `js/plugin.js` which will be fixed in the next release one of these days. If you want to hack it in yourself you can apply this patch, either manually or by using the `patch` command (which also includes some unrelated other fixes staged for the next release):

```diff
diff --git a/files_reader/js/plugin.js b/files_reader/js/plugin.js
index 5c4bc3e..5a6323a 100644
--- a/files_reader/js/plugin.js
+++ b/files_reader/js/plugin.js
@@ -135,7 +135,7 @@
 
             if (oc_appconfig.filesReader.enableEpub === 'true')
                 fileActions.setDefault('application/epub+zip', 'view-epub');
-            if (oc_appconfig.filesReader.enableCbr === 'true')
+            if (oc_appconfig.filesReader.enableCbx === 'true')
                 fileActions.setDefault('application/x-cbr', 'view-cbr');
             if (oc_appconfig.filesReader.enablePdf === 'true')
                 fileActions.setDefault('application/pdf', 'view-pdf');
@@ -148,7 +148,11 @@ OC.Plugins.register('OCA.Files.FileList', OCA.Files_Reader.Plugin);
 
 // FIXME: Hack for single public file view since it is not attached to the fileslist
 $(document).ready(function(){
-       if ($('#isPublic').val() && ($('#mimetype').val() === 'application/epub+zip'|| $('#mimetype').val() === 'application/x-cbr)')) {
+       if ($('#isPublic').val()
+        && ($('#mimetype').val() === 'application/epub+zip'
+            || $('#mimetype').val() === 'application/pdf'
+            || $('#mimetype').val() === 'application/x-cbr')
+        ) {
                var sharingToken = $('#sharingToken').val();
                var downloadUrl = OC.generateUrl('/s/{token}/download', {token: sharingToken});
                var viewer = OCA.Files_Reader.Plugin;
diff --git a/files_reader/lib/Controller/PageController.php b/files_reader/lib/Controller/PageController.php
index 3306292..14b2224 100644
--- a/files_reader/lib/Controller/PageController.php
+++ b/files_reader/lib/Controller/PageController.php
@@ -135,7 +135,7 @@ class PageController extends Controller {
      */ 
     private function getFileInfo($path) {
         $count = 0;
-        $shareToken = preg_replace("/(?:\/index\.php)?\/s\/([A-Za-z0-9]{15})\/download.*/", "$1", $path, 1,$count);
+        $shareToken = preg_replace("/(?:\/index\.php)?\/s\/([A-Za-z0-9]{15,32})\/download.*/", "$1", $path, 1,$count);
 
         if ($count === 1) {
```

**Comment by Yetangitu** [comment] 2018-02-24 23:17
Fixed in v1.2.3

**Closed by Yetangitu** 2018-02-24 23:17 UTC

**Comment by BodoWitcha** [comment] 2018-08-14 20:25
I have installed files_reader v1.2.3  on Nextcloud  v13.0.5.2  fresh  and upgraded on 2 different boxes.
CBR/CBR files are rendered as shown by returntrip commented on 15 Feb in this post.
Because this post is closed, can this post being reopened or should I start a new one?

**Comment by Slevin7** [comment] 2018-08-15 10:16
Your workaround unfortunately leads to a login loop on Chrome.
If the login loop happens to somebody else, you have to switch back to false and delete your cookies.

**Comment by Slevin7** [comment] 2018-08-15 10:25
@BodoWitcha i should have test it first to ^^.
but maybe it was also on my system, I think the workaround should have other testing.
